/*   STEP 1   */
export const leagueID = "1312159501335416832"; // your league ID (2026 season)
export const leagueName = "ACT, or Die."; // your league name
export const dues = 100; // (optional) used in template constitution page
export const dynasty = true; // true for dynasty leagues, false for redraft and keeper
export const enableBlog = false; // requires VITE_CONTENTFUL_ACCESS_TOKEN and VITE_CONTENTFUL_SPACE environment variables

/*   STEP 2   */
export const homepageText = `
<p>Welcome to the ACT, or DIE. Dynasty League. This is a 12-team league that was formed mid-season in
2018 for our more dedicated fantasy football playing friends as a place to compete against each other in
a challenging and long-term setting. This is a dynasty league, meaning that owners will keep ALL the
players on their team from year to year. This league is considered a prize money league, and all owners
are expected to pay their league fee before the league fee deadline (start of the NFL regular season).
There may be a late fee assessed after the deadline. This league is designed to be a competitive league
between friends but is not a cut-throat league where anything goes. </p>
`;

export const dreamDraftLocationImages = {
  "Charleston, SC": "/dreamLocations/charleston.png",
  "Beach": "/dreamLocations/beach.png",
  "All-Inclusive Island Resort": "/dreamLocations/island.png",
  "Vegas": "/dreamLocations/vegas.png",
  "Vegas, baby!": "/dreamLocations/vegas.png",
  "Vegas (would love to host one day)": "/dreamLocations/vegas.png",
  "Pittsburgh": "/dreamLocations/pittsburgh.png",
  "The Burgh! (already did it)": "/dreamLocations/pittsburgh.png",
  "Anywhere": "/dreamLocations/anywhere.png",
  "Just wanna hang with the squad": "/dreamLocations/anywhere.png",
  "Ha, I'm not sure": "/dreamLocations/anywhere.png",
  "Hawaii": "/dreamLocations/hawaii.png",
  "The Sphere": "/dreamLocations/sphere.png",
  "Australia": "/dreamLocations/australia.png",
};

export const beverageImages = {
  "IPA": "/beverages/ipa.png",
  "Hazy IPAs": "/beverages/ipa.png",
  "Coors Light": "/beverages/coors-light.png",
  "Ice Cold Coors Light": "/beverages/coors-light.png",
  "Negroni": "/beverages/negroni.png",
  "Bourbon": "/beverages/bourbon.png",
  "Smokey Scotch": "/beverages/smokey-scotch.png",
  "IPA or Smokey Scotch": "/beverages/smokey-scotch.png",
  "Chocolate Milk": "/beverages/chocolate-milk.png",
  "Chocolate Milk or Vodka Redbull": "/beverages/chocolate-milk.png",
  "Old Fashioned": "/beverages/old-fashioned.png",
  "Dos Equis with Lime": "/beverages/dos-equis.png",
  "Beer": "/beverages/beer.png",
  "Vodka Redbull": "/beverages/vodka-redbull.png",
};

/*   STEP 3   */
/*
3 managers as an example. Uncomment (remove the //) before each line to make it live code
If you're having trouble, reference the Training Wheels' Manager Section
https://github.com/nmelhado/league-page/blob/master/TRAINING_WHEELS.md#ii-adding-managers-and-changing-the-homepage-text
*/

// To omit an optional field, set it's value to null

export const managers = [
  {
    "roster": 1,
    "managerID": "351393281512570880",
    "name": "Lee Trask",
    "tookOver": null,
    "location": "Greenville, SC",
    "bio": null,
    "photo": "/managers/lee.png",
    "fantasyStart": null,
    "favoriteTeam": "cle",
    "mode": "Rebuild",
    "rival": {
      "name": "Laue",
      "link": 3,
      "image": "/managers/laue.png",
    },
    "favoritePlayer": 3973,
    "valuePosition": "WR",
    "rookieOrVets": "Rookies",
    "philosophy": null,
    "tradingScale": 4,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "Bucky Irving",
    "sideBetInterest": 7,
    "beverage": "IPA",
    "dreamDraftLocation": "Charleston, SC",
    "phoneNumber": "920-221-6040",
  },
  {
    "roster": 1,
    "managerID": "325681665881935872",
    "name": "Keith Brinsko",
    "tookOver": null,
    "location": "Minnesota",
    "bio": null,
    "photo": "/managers/keith.png",
    "fantasyStart": null,
    "favoriteTeam": "pit",
    "mode": "Survive + Vibes",
    "rival": {
      "name": "Literally Everyone",
      "link": null,
      "image": "/managers/everyone.png",
    },
    "favoritePlayer": 4070,
    "valuePosition": "WR",
    "rookieOrVets": "Rookies",
    "philosophy": null,
    "tradingScale": 7,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "Drake Maye",
    "sideBetInterest": 9,
    "beverage": "Old Fashioned",
    "dreamDraftLocation": "Hawaii",
    "phoneNumber": "863-289-2445",
  },
  {
    "roster": 2,
    "managerID": "351402869095911424",
    "name": "Aaron Murnan",
    "tookOver": null,
    "location": "Columbus",
    "bio": null,
    "photo": "/managers/aaron.png",
    "fantasyStart": null,
    "favoriteTeam": "cle",
    "mode": "Win Now",
    "rival": {
      "name": "Laue",
      "link": 3,
      "image": "/managers/laue.png",
    },
    "favoritePlayer": 11632,
    "valuePosition": "WR",
    "rookieOrVets": "Vets (right now)",
    "philosophy": null,
    "tradingScale": 10,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "Jonathan Taylor",
    "sideBetInterest": 8,
    "beverage": "Negroni",
    "dreamDraftLocation": "Beach",
    "phoneNumber": "440-371-7129",
  },
  {
    "roster": 3,
    "managerID": "360567604319936512",
    "name": "Bryan Laue",
    "tookOver": null,
    "location": "Cleveland, OH",
    "bio": null,
    "photo": "/managers/laue.png",
    "fantasyStart": null,
    "favoriteTeam": "cle",
    "mode": "Survive + Vibes",
    "rival": {
      "name": "Aaron",
      "link": 2,
      "image": "/managers/aaron.png",
    },
    "favoritePlayer": 4984,
    "valuePosition": "WR",
    "rookieOrVets": "Vets",
    "philosophy": null,
    "tradingScale": 7,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "Josh Allen",
    "sideBetInterest": 7,
    "beverage": "Bourbon",
    "dreamDraftLocation": "All-Inclusive Island Resort",
    "phoneNumber": "614-917-3799",
  },
  {
    "roster": 4,
    "managerID": "361001391055187968",
    "name": "tarmstrong20",
    "tookOver": null,
    "location": null,
    "bio": null,
    "photo": "/managers/tarmstrong20.png",
    "fantasyStart": null,
    "favoriteTeam": null,
    "mode": null,
    "rival": {
      "name": "?",
      "link": null,
      "image": "/managers/question.jpg",
    },
    "favoritePlayer": null,
    "valuePosition": null,
    "rookieOrVets": null,
    "philosophy": null,
    "tradingScale": null,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": null,
    "sideBetInterest": null,
    "beverage": null,
    "dreamDraftLocation": null,
    "phoneNumber": null,
  },
  {
    "roster": 5,
    "managerID": "730578604303474688",
    "name": "Steven Willke",
    "tookOver": null,
    "location": "Columbus",
    "bio": null,
    "photo": "/managers/swillke.png",
    "fantasyStart": null,
    "favoriteTeam": "cin",
    "mode": "Rebuild",
    "rival": {
      "name": "Murnan",
      "link": 2,
      "image": "/managers/aaron.png",
    },
    "favoritePlayer": 9488,
    "valuePosition": "RB",
    "rookieOrVets": "Roomies",
    "philosophy": null,
    "tradingScale": 7,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "JSN",
    "sideBetInterest": 4,
    "beverage": "Beer",
    "dreamDraftLocation": "Ha, I'm not sure",
    "phoneNumber": "908-399-7802",
  },
  {
    "roster": 6,
    "managerID": "361223214527168512",
    "name": "Alex Campbell",
    "tookOver": null,
    "location": "Seattle",
    "bio": null,
    "photo": "/managers/cambysoup.png",
    "fantasyStart": null,
    "favoriteTeam": "cle",
    "mode": "Survive + Vibes",
    "rival": {
      "name": "Title Chase (Murnan)",
      "link": 2,
      "image": "/managers/aaron.png",
    },
    "favoritePlayer": 294,
    "valuePosition": "RB",
    "rookieOrVets": null,
    "philosophy": null,
    "tradingScale": 6,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "Joe Cool / Joe Brrr / Joe Shiesty",
    "sideBetInterest": 5,
    "beverage": "Hazy IPAs",
    "dreamDraftLocation": "The Sphere",
    "phoneNumber": "419-461-0713",
  },
  {
    "roster": 7,
    "managerID": "361238276541304832",
    "name": "Jacob Schwinn",
    "tookOver": null,
    "location": "The very large city of Nova, Ohio",
    "bio": null,
    "photo": "/managers/jacob.png",
    "fantasyStart": null,
    "favoriteTeam": "cle",
    "mode": "Win Now",
    "rival": {
      "name": "Lee",
      "link": 1,
      "image": "/managers/lee.png",
    },
    "favoritePlayer": 12524,
    "valuePosition": "RB",
    "rookieOrVets": "A sucker for Rookies",
    "philosophy": null,
    "tradingScale": 8,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "Saquon - my first pick in the startup draft",
    "sideBetInterest": 4,
    "beverage": "Ice Cold Coors Light",
    "dreamDraftLocation": "Vegas (would love to host one day)",
    "phoneNumber": "330-904-2508",
  },
  {
    "roster": 8,
    "managerID": "361311292944093184",
    "name": "David Bortz",
    "tookOver": null,
    "location": "Pittsburgh",
    "bio": null,
    "photo": "/managers/david.png",
    "fantasyStart": null,
    "favoriteTeam": "phi",
    "mode": "Win Now",
    "rival": {
      "name": "Obviously Aaron",
      "link": 2,
      "image": "/managers/aaron.png",
    },
    "favoritePlayer": 12481,
    "valuePosition": "RB",
    "rookieOrVets": "Rookies",
    "philosophy": null,
    "tradingScale": 9,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "Cam Skattebo",
    "sideBetInterest": 10,
    "beverage": "IPA or Smokey Scotch",
    "dreamDraftLocation": "The Burgh! (already did it)",
    "phoneNumber": "740-381-6198",
  },
  {
    "roster": 9,
    "managerID": "361673241473007616",
    "name": "Lyndsey McMasters",
    "tookOver": null,
    "location": "Dublin, OH",
    "bio": null,
    "photo": "/managers/mcmath15.png",
    "fantasyStart": null,
    "favoriteTeam": "cle",
    "mode": "Win Now",
    "rival": {
      "name": "Aaron's Behemoth Squad",
      "link": 2,
      "image": "/managers/aaron.png",
    },
    "favoritePlayer": 11566,
    "valuePosition": "RB",
    "rookieOrVets": "Rookies",
    "philosophy": null,
    "tradingScale": 8,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "Jayden Daniels",
    "sideBetInterest": 8,
    "beverage": "Dos Equis with Lime",
    "dreamDraftLocation": "Vegas, baby!",
    "phoneNumber": "330-407-4349",
  },
  {
    "roster": 10,
    "managerID": "758878550358093824",
    "name": "Cyres Cooper",
    "tookOver": null,
    "location": "Columbus, OH",
    "bio": null,
    "photo": "/managers/cyres.png",
    "fantasyStart": null,
    "favoriteTeam": "min",
    "mode": "Survive + Vibes",
    "rival": {
      "name": "Aaron",
      "link": 2,
      "image": "/managers/aaron.png",
    },
    "favoritePlayer": 9493,
    "valuePosition": "TE",
    "rookieOrVets": "Rookies",
    "philosophy": null,
    "tradingScale": 10,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "Puka",
    "sideBetInterest": 8,
    "beverage": "Chocolate Milk or Vodka Redbull",
    "dreamDraftLocation": "Just wanna hang with the squad",
    "phoneNumber": "937-631-4074",
  },
  {
    "roster": 10,
    "managerID": "835653138768826368",
    "name": "Reed Cooper",
    "tookOver": null,
    "location": "Chicago",
    "bio": null,
    "photo": "/managers/cooperr4.png",
    "fantasyStart": null,
    "favoriteTeam": "car",
    "mode": "Win Now",
    "rival": {
      "name": "KV",
      "link": 12,
      "image": "/managers/kvaitkus.png",
    },
    "favoritePlayer": 9221,
    "valuePosition": "TE",
    "rookieOrVets": "Rookies",
    "philosophy": null,
    "tradingScale": 10,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "Rico Dowdle",
    "sideBetInterest": 7,
    "beverage": "Vodka Redbull",
    "dreamDraftLocation": "Australia",
    "phoneNumber": "937-450-4140",
  },
  {
    "roster": 11,
    "managerID": "1028127554101735424",
    "name": "BStephens89",
    "tookOver": null,
    "location": null,
    "bio": null,
    "photo": "/managers/bstephens.png",
    "fantasyStart": null,
    "favoriteTeam": null,
    "mode": null,
    "rival": {
      "name": "?",
      "link": null,
      "image": "/managers/question.jpg",
    },
    "favoritePlayer": null,
    "valuePosition": null,
    "rookieOrVets": null,
    "philosophy": null,
    "tradingScale": null,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": null,
    "sideBetInterest": null,
    "beverage": null,
    "dreamDraftLocation": null,
    "phoneNumber": null,
  },
  {
    "roster": 12,
    "managerID": "362443399300825088",
    "name": "Kristian Vaitkus",
    "tookOver": null,
    "location": "Cleveland, OH",
    "bio": null,
    "photo": "/managers/kvaitkus.png",
    "fantasyStart": null,
    "favoriteTeam": "cle",
    "mode": "Survive + Vibes",
    "rival": {
      "name": "Cyres",
      "link": 10,
      "image": "/managers/cyres.png",
    },
    "favoritePlayer": 167,
    "valuePosition": "QB",
    "rookieOrVets": "Vets",
    "philosophy": null,
    "tradingScale": 1,
    "preferredContact": "Text",
    "favoritePlayerOnRoster": "Dak Prescott",
    "sideBetInterest": 1,
    "beverage": null,
    "dreamDraftLocation": "Australia",
    "phoneNumber": "216-534-5072",
  },
];

/*   !!  !!  IMPORTANT  !!  !! */
/*
  Below is the most up to-date version of a manager. Please leave this commented out
  and don't delete it. This will be updated if any fields are added, removed or changed
  and will allow updates without causing merge conflicts
  */
  
    // {
    //   "roster": 3,  // (DEPRECATED! Don't use this anymore) ID of the roster that the manager manages (look at the order of the power rankings graph)
    //   "managerID": "12345678",  // the user's manager ID, go to https://api.sleeper.app/v1/league/<your_league_id>/users to find user IDs (you can use older leagueIDs to find user IDs for managers that are no longer in the league)
    //   "name": "Your Name",
    //   "tookOver": 2020, // (DEPRECATED! You don't need to use this anymore) (optional) used if a manager took over a team, delete this line or change to null otherwise
    //   "location": "Brooklyn", // (optional)
    //   "bio": "Lorem ipsum...",
    //   "photo": "/managers/name.jpg", // square ratio recommended (no larger than 500x500)
    //   "fantasyStart": 2014, // (optional) when did the manager start playing fantasy football
    //   "favoriteTeam": "nyj", // (optional) favorite NFL team, (follows convention: nyj, sea, mia, etc.) MUST BE LOWERCASE
    //   "mode": "Win Now", // (optional) 'Win Now', 'Rebuild', or 'Survive + Vibes' (anything else and you will need to add a new png to /static/ similar to the 'Rebuild.png' and 'Win Now.png' currently in there)
    //   "rival": {
    //     name: "Rival", // Can be anything (usually your rival's name)
    //     link: 6, // manager array number within this array, or null to link back to all managers page
    //     image: "/managers/rival.jpg", // either a specific manager photo or '/managers/everyone.png' or '/managers/question.png'
    //   },
    //   "favoritePlayer": 1426, // (optional) this corresponds to the Sleeper player ID (https://api.sleeper.app/v1/players/nfl)
    //   "valuePosition": "WR", // (optional) Favorite position (QB, WR, RB, TE, etc.)
    //   "rookieOrVets": "Rookies", // (optional) 'Rookies' or 'Vets' (anything else and you will need to add a new png to /static/ similar to the 'Rookies.png' and 'Vets.png' currently in there)
    //   "philosophy": "Your fantasy team's philosophy", // (optional)
    //   "tradingScale": 10, // 1 - 10 (optional)
    //   "preferredContact": "Text",  // (optional) 'Text', 'WhatsApp', 'Sleeper', 'Email', 'Phone', 'Discord', and 'Carrier Pigeon' are currently supplied in the template
    // },
